version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.17
    restart: "no"
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: host.docker.internal
            port: 5432
            database: testi
            schema: public
            user: postgres
            password: admin
            migrations: false
            ssl: false
